name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: "Set version number"
        run: |
          python3 ${{ github.workspace }}/.github/helpers/update_manifest.py --version ${GITHUB_REF##*/}

      - name: Combine ZIP
        run: |
          cd ${{ github.workspace }}/custom_components/frank_energie
          zip frank_energie.zip -r ./

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/frank_energie/frank_energie.zip
